### PR TITLE
Fix setup.py file

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
This means we have inline source maps, we should consider reverting that, it grows the bundle quite a bit! I should check for ipyvolume as well.

**Comment by martinRenou** [comment]
Ok :) I would be happy to revert it. But should the source maps be deployed by the `setup.py` anyway?

**Comment by maartenbreddels** [comment]
Not sure, for debugging it makes sense to have, lets revert it to what it was, and determine widget wise what we should do.

**Comment by SylvainCorlay** [comment]
Merging as it fixes the build in master.

I am fine with re-adding source maps later.

**Comment by martinRenou** [comment]
@maartenbreddels In order to put the mapping file back I just need to remove the `inline-source-map` option in the karma config right?

**Comment by maartenbreddels** [comment]
No, I think you replace by source-map, and include the files again in setup.py

**Comment by martinRenou** [comment]
Ok :) Thanks, will do that

**Pull request merged**
