### PR TITLE
JupyterLab 3 Update

### PR DESCRIPTION
**Pull request by jabbera**
This modernizes ipysheet for JL3 and makes it a prebuilt extension simplifying the install steps. Unknown what it means for older installations ci cd etc, but others may be interested in the work.

### CODE REVIEW

**Comment by martinRenou** [comment]
Thanks a lot for the update! And sorry for not looking at it earlier.

It seems to work perfectly on my side. Will merge and test further.

**Comment by agoose77** [comment]
@martinRenou I could be wrong (am on mobile), but last time I checked it looked like this pr dropped support for Jupyter Notebook. Is that intentional?

**Comment by martinRenou** [comment]
You're not wrong... I realized it too late.

I am currently adding it back.

**Comment by iwansetwan** [comment]
I just update my jupyterlab to 3.2.1

I get this error

Error displaying widget: model not found

Can somebody help?

**Comment by stefaneidelloth** [comment]
Related: https://github.com/QuantStack/ipysheet/issues/202

**Pull request merged**
