### PR TITLE
Fix render on undefined error

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Do you know which path is causing this?

**Comment by maartenbreddels** [comment]
I'm afraid that it is in the 'after-show' msg and that it will cause the table not to layout correctly.

**Comment by martinRenou** [comment]
I am not sure but I also think it's after the 'after-show' event

> I'm afraid [...] it will cause the table not to layout correctly

Well if it's undefined the function crashes anyway so I'm not really changing the code behavior here. Just preventing an error in the console.

**Comment by maartenbreddels** [comment]
it's at the resize event, and I think it's better we use the `_table_constructed` promise to make sure we render it.

**Comment by martinRenou** [comment]
I agree with you, so I simply removed `table_render` so that it's not called when it should not be

**Pull request merged**
