### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Awesome work! I don't really recognize the docstrings as being a particular standard, can you elaborate on the chosen style?
Also, I prefer api.rst (it gives a much cleaner url), also, any reason to rename it? The caption/title is taken from the 'h1/h2', which is given already:
```
API reference
=============
```
(I can push the change for the renaming back if you want)

**Comment by martinRenou** [comment]
> Awesome work! I don't really recognize the docstrings as being a particular standard, can you elaborate on the chosen style?

Thanks :) I found it on this page: https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example. I tried it and found that the generated HTML looked better :) If you would like to use another standard I'm fine with changing it.

I also prefer `api.rst`, I think I renamed it when trying to change the documentation section title, we can rename it back :)

**Comment by maartenbreddels** [comment]
> I found it on this page: https://pythonhosted.org/an_example_pypi_project/sphinx.html#full-code-example.

I think you are mixing google and sphinx style. What I don't like about the google style is that it contains so much vertical waste since docstrings in jupyter are not HTML rendered, the plain text formatting still matters. In any case, I would drop the `Kwargs`, since the distinction isn't really meaningful.  See also https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

> I think I renamed it when trying to change the documentation section title, we can rename it back :)

that's what I guessed, yeah, if you could do that, awesome!

**Comment by martinRenou** [comment]
> since the distinction isn't really meaningful

Why do you think it is not meaningful? I think it matters for the user

**Comment by maartenbreddels** [comment]
I mean, if there was a  `**kwargs`, a section like that makes sense, for the rest I see no added value between argument with and without default values. I've never seen this in docs, it's also not used here https://google.github.io/styleguide/pyguide.html#doc-function-raises (example directly below)



> if you have a standard

Since we're close to it, lets stay with google https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings

**Comment by martinRenou** [comment]
@maartenbreddels widgets are not visible in the documentation: https://ipysheet.readthedocs.io/en/latest/. There's a JS error. I'm not sure how to fix it

**Comment by maartenbreddels** [comment]
I see I'll take a look at it.

Btw, my standard workflow for working on the docs is to have a 'docs' branch in the main repo, have rtd set up to build that, and push directly to that branch (instead of our own fork). The rest is the name, you can just open a PR from the main repo docs branch into master.

Unless you have a better idea, I suggest to close this PR, push this branch to upstream/docs, and I'll set up rtd. Sound good?

**Comment by martinRenou** [comment]
Sounds good :) I'll do that

**Pull request closed without merging**
