### PR TITLE
Add Jupyterlab theme support

### LINKED ISSUE #52: Jupyterlab theming
We should add support for JupyterLab theming

### PR DESCRIPTION
**Pull request by martinRenou**
Should fix #52

### CODE REVIEW

**Comment by martinRenou** [comment]
theming

**Comment by maartenbreddels** [comment]
Really nice! I see there are some files copied from jupyter-widgets right? Would be nice if we could avoid that (I'll look into it).

**Comment by martinRenou** [comment]
Maybe an `import '@jupyter-widgets/controls/css/materialcolors.css';` can do the trick

**Comment by maartenbreddels** [comment]
We will have to depend on @jupyter-widgets/controls, but I'm ok with that.

**Comment by maartenbreddels** [comment]
Awesome work btw! How did you attack the problem (just in case someone wants to do something similar)?

**Comment by martinRenou** [comment]
Thanks :)
Well it is not too difficult, you just need to patiently go through all the CSS classes from stylesheets of the JavaScript library you are using (here Handsontable stylesheets and pikaday stylesheets) and create new CSS classes that will replace the text color/background color/font size etc using the JupyterLab CSS variables defined in https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/controls/css/labvariables.css

**Comment by martinRenou** [comment]
BTW, those stylesheet files that we now import from `@jupyter-widgets/controls` were already copied from JupyterLab.. Maybe we could think of a better way of doing it. The thing is the user might not have JupyterLab installed, that's why ipywidgets has a copy of this file

**Comment by maartenbreddels** [comment]
There is a small difference:
https://github.com/jupyter-widgets/ipywidgets/blob/092c085aaf3b1165a5c8f24a9ce663ae523e7969/packages/controls/css/labvariables.css#L40

I'm ok with depending on this particular file set, since whatever the original source is, what works for ipywidgets, will work for us right? Also, if it changes, it should give us a travis build fail.

**Pull request merged**
