### PR TITLE
Fix CI environment

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by maartenbreddels** [comment]
not sure why it still does not find flexx.pyscript for py!=2.7

**Comment by martinRenou** [comment]
@maartenbreddels I don't know if you agree with those changes. I removed the optional dependency for `flexx`, and replaced it by `pscript` which is the exact package that we want, it's just that it does not bring the whole `flexx` with it.

**Comment by maartenbreddels** [comment]
Yes, should be fine is that is how the library evolved, as long as it works. Strange error msg now btw.

**Comment by martinRenou** [comment]
Nooooo :'(. I don't get it, I just rebased. I was working yesterday

**Comment by martinRenou** [comment]
I guess it's because of the new release of ipywidgets

**Comment by martinRenou** [comment]
Yes it was due to the release of ipywidgets, it did not use the same version of typescript I guess. Updating typescript fixed it :)

**Comment by maartenbreddels** [comment]
Great, so it needed typescript 3?

**Comment by martinRenou** [comment]
Well, typescript could not build ipywidgets (And I don't really understand why it needs to). So I updated the version of Typescript to the same as in ipywidgets. Thanks for the merge!

**Pull request merged**
